name: Coverage
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches-ignore:
      - master
      - develop
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: coverage
        run: make coverage
