name: Security
on:
  push:
    branches:
      - master
      - develop
  pull_request:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: security
        run: make security
